### ISSUE TITLE
[CloudDesigner]When running eclipse from CloudDesigner, some mylyn dependencies not found

### ISSUE THREAD

**Issue by cgourdin** [occiware/ecore#178]
This is maybe due to the migration on Eclipse Neon version. 
Trace:
`!SESSION 2016-11-03 09:14:51.199 -----------------------------------------------
eclipse.buildId=4.6.1.M20160907-1200
java.version=1.8.0_71
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=fr_FR
Framework arguments:  -product org.eclipse.platform.ide
Command-line arguments:  -product org.eclipse.platform.ide -data /Users/cgourdin/workspace_scalair_demo -dev file:/Users/cgourdin/workspace_connector2/.metadata/.plugins/org.eclipse.pde.core/Eclipse Application/dev.properties -os macosx -ws cocoa -arch x86_64 -consoleLog

!ENTRY org.eclipse.mylyn.context.core 4 0 2016-11-03 09:14:51.903
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.mylyn.context.core [4979]
  Unresolved requirement: Import-Package: org.apache.commons.io; version="[1.4.0,3.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1599)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.mylyn.context.ui 4 0 2016-11-03 09:14:51.908
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.mylyn.context.ui [4980]
  Unresolved requirement: Require-Bundle: org.eclipse.mylyn.monitor.ui; bundle-version="[3.8.0,4.0.0)"
    -> Bundle-SymbolicName: org.eclipse.mylyn.monitor.ui; bundle-version="3.20.0.v20160421-1819"; singleton:="true"
       org.eclipse.mylyn.monitor.ui [4984]
         Unresolved requirement: Require-Bundle: org.eclipse.mylyn.context.core; bundle-version="[3.0.0,4.0.0)"
           -> Bundle-SymbolicName: org.eclipse.mylyn.context.core; bundle-version="3.20.0.v20160421-1902"; singleton:="true"
              org.eclipse.mylyn.context.core [4979]
                Unresolved requirement: Import-Package: org.apache.commons.io; version="[1.4.0,3.0.0)"
  Unresolved requirement: Require-Bundle: org.eclipse.mylyn.context.core; bundle-version="[3.8.0,4.0.0)"
    -> Bundle-SymbolicName: org.eclipse.mylyn.context.core; bundle-version="3.20.0.v20160421-1902"; singleton:="true"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1599)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.mylyn.monitor.ui 4 0 2016-11-03 09:14:51.911
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.mylyn.monitor.ui [4984]
  Unresolved requirement: Require-Bundle: org.eclipse.mylyn.context.core; bundle-version="[3.0.0,4.0.0)"
    -> Bundle-SymbolicName: org.eclipse.mylyn.context.core; bundle-version="3.20.0.v20160421-1902"; singleton:="true"
       org.eclipse.mylyn.context.core [4979]
         Unresolved requirement: Import-Package: org.apache.commons.io; version="[1.4.0,3.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1599)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.mylyn.tasks.ui 4 0 2016-11-03 09:14:51.915
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.mylyn.tasks.ui [4989]
  Unresolved requirement: Require-Bundle: org.eclipse.mylyn.monitor.ui; bundle-version="3.8.0"
    -> Bundle-SymbolicName: org.eclipse.mylyn.monitor.ui; bundle-version="3.20.0.v20160421-1819"; singleton:="true"
       org.eclipse.mylyn.monitor.ui [4984]
         Unresolved requirement: Require-Bundle: org.eclipse.mylyn.context.core; bundle-version="[3.0.0,4.0.0)"
           -> Bundle-SymbolicName: org.eclipse.mylyn.context.core; bundle-version="3.20.0.v20160421-1902"; singleton:="true"
              org.eclipse.mylyn.context.core [4979]
                Unresolved requirement: Import-Package: org.apache.commons.io; version="[1.4.0,3.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1599)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.mylyn.wikitext.context.ui 4 0 2016-11-03 09:14:51.917
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.mylyn.wikitext.context.ui [4992]
  Unresolved requirement: Require-Bundle: org.eclipse.mylyn.context.ui; bundle-version="3.7.0"
    -> Bundle-SymbolicName: org.eclipse.mylyn.context.ui; bundle-version="3.20.0.v20160421-1902"; singleton:="true"
       org.eclipse.mylyn.context.ui [4980]
         Unresolved requirement: Require-Bundle: org.eclipse.mylyn.context.core; bundle-version="[3.8.0,4.0.0)"
           -> Bundle-SymbolicName: org.eclipse.mylyn.context.core; bundle-version="3.20.0.v20160421-1902"; singleton:="true"
              org.eclipse.mylyn.context.core [4979]
                Unresolved requirement: Import-Package: org.apache.commons.io; version="[1.4.0,3.0.0)"
  Unresolved requirement: Require-Bundle: org.eclipse.mylyn.context.core; bundle-version="3.7.0"
    -> Bundle-SymbolicName: org.eclipse.mylyn.context.core; bundle-version="3.20.0.v20160421-1902"; singleton:="true"
  Unresolved requirement: Require-Bundle: org.eclipse.mylyn.monitor.ui; bundle-version="3.7.0"
    -> Bundle-SymbolicName: org.eclipse.mylyn.monitor.ui; bundle-version="3.20.0.v20160421-1819"; singleton:="true"
       org.eclipse.mylyn.monitor.ui [4984]
         Unresolved requirement: Require-Bundle: org.eclipse.mylyn.context.core; bundle-version="[3.0.0,4.0.0)"
           -> Bundle-SymbolicName: org.eclipse.mylyn.context.core; bundle-version="3.20.0.v20160421-1902"; singleton:="true"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1599)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.mylyn.wikitext.tasks.ui 4 0 2016-11-03 09:14:51.922
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.mylyn.wikitext.tasks.ui [5002]
  Unresolved requirement: Require-Bundle: org.eclipse.mylyn.tasks.ui; bundle-version="3.7.0"
    -> Bundle-SymbolicName: org.eclipse.mylyn.tasks.ui; bundle-version="3.20.0.v20160608-1838"; singleton:="true"
       org.eclipse.mylyn.tasks.ui [4989]
         Unresolved requirement: Require-Bundle: org.eclipse.mylyn.monitor.ui; bundle-version="3.8.0"
           -> Bundle-SymbolicName: org.eclipse.mylyn.monitor.ui; bundle-version="3.20.0.v20160421-1819"; singleton:="true"
              org.eclipse.mylyn.monitor.ui [4984]
                Unresolved requirement: Require-Bundle: org.eclipse.mylyn.context.core; bundle-version="[3.0.0,4.0.0)"
                  -> Bundle-SymbolicName: org.eclipse.mylyn.context.core; bundle-version="3.20.0.v20160421-1902"; singleton:="true"
                     org.eclipse.mylyn.context.core [4979]
                       Unresolved requirement: Import-Package: org.apache.commons.io; version="[1.4.0,3.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1599)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.ui.intro.universal 4 0 2016-11-03 09:14:51.929
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.ui.intro.universal [5155]
  Unresolved requirement: Require-Bundle: org.eclipse.ui.intro.quicklinks; bundle-version="1.0.0"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1599)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.core.net 1 0 2016-11-03 09:14:55.838
!MESSAGE System property http.nonProxyHosts has been set to local|*.local|169.254/16|*.169.254/16 by an external source. This value will be overwritten using the values from the preferences
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
log4j:WARN No appenders could be found for logger (com.vmware.vim25.ws.XmlGenDom).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
`

**Comment by cgourdin** [comment]
I have solved this problem with "Run Configuration" --> eclipse plugin --> added the missing dependencies. 
But SLF4j doesn't initialize correctly.

**Comment by cgourdin** [comment]
SLF4J problem : 

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
