### ISSUE TITLE
Clouddesigner erro when generated EMF Tooling

### ISSUE THREAD

**Issue by fifiant** [occiware/ecore#19]
When I'm trying to generate the "EMF Tooling" from the Clouddesigner I got this error:

```java
java.lang.NullPointerException
	at org.eclipse.emf.ecore.impl.EStructuralFeatureImpl.setDefaultValue(EStructuralFeatureImpl.java:161)
	at org.occiware.clouddesigner.occi.emfgen.OCCIExtension2Ecore.convertAttribute(OCCIExtension2Ecore.java:156)
	at org.occiware.clouddesigner.occi.emfgen.OCCIExtension2Ecore.convertKind(OCCIExtension2Ecore.java:113)
	at org.occiware.clouddesigner.occi.emfgen.OCCIExtension2Ecore.convertExtension(OCCIExtension2Ecore.java:62)
	at org.occiware.clouddesigner.occi.emfgen.ui.popup.actions.ConvertAction.generateEMFModels(ConvertAction.java:147)
	at org.occiware.clouddesigner.occi.emfgen.ui.popup.actions.ConvertAction.run(ConvertAction.java:90)
	at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:247)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
```

Do you have any idea ?

**Comment by wpiers** [comment]
here his the code:
EAttribute eAttr = EcoreFactory.eINSTANCE.createEAttribute();
		eAttr.setName(ConverterUtils.formatName(attribute.getName()));
		eAttr.setEType(getActualType(attribute.getType()));
		String defaultValue = attribute.getDefault();
		if (defaultValue != null && !defaultValue.isEmpty()) {
(156)			eAttr.setDefaultValue(defaultValue);
		}

So I don't know how this happen, eAttr cannot be null at this point. Could you attach the .occie file to this issue ? Thanks in advance

**Comment by philippemerle** [comment]
Yes this is a bug, the EMF Tooling generator does not dealt with imported datatypes correctly.
This is an urgent bug to resolve in order to update the Docker extension for supporting Docker 1.9 networking features.
+1

**Comment by philippemerle** [comment]
William: in fact the NullPointerException should be thrown inside  eAttr.setDefaultValue() and eAttr != null
the problem is in getActualType() when the OCCI type is imported then getActualType returns null.

**Comment by fifiant** [comment]
This is my "cloud.occie" file https://gist.github.com/fifiant/35c9d48a4a7e9fe3a34f

Thanks.

**Comment by philippemerle** [comment]
Fawaz: please, could you check that the new Extension2Ecore transformation works well for your cloud extension?

**Comment by fifiant** [comment]
@philippemerle, your fix on the Extension2Ecore transformation works for my cloud extension.
Thank.
