### ISSUE TITLE
Mart : example in the README.md is not working

### ISSUE THREAD

**Issue by MaelAudren** [occiware/ecore#204]
In /occiware/ecore/
In the README.md :
Execute the example without EMF/OCL validation:
	mvn exec:java"

$ mvn exec:java
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.occiware.mart.MART.<clinit>(MART.java:51)
	at org.occiware.mart.Main.main(Main.java:49)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by Xia0ben** [comment]
Looks like this subproject has been deprecated, since no commits have been added for more than a year. Looks like you're trying to get the CloudDesigner on your dev env, if so, I recommend you to check http://occiware.github.io/ , and particularly http://occiware.github.io/content/developer-guides/snapshot/studio-setting-up-the-environment.html . I updated the content a lot when I arrived on this project two months ago, with that, you should be able to get everything up and running in no time ;-).
