### ISSUE TITLE
Error while modify model

### ISSUE THREAD

**Issue by fifiant** [occiware/ecore#74]
Hi,

I did an update last yesterday. In my Docker Configuration when I dragged a machine, I have this error:

```

!ENTRY org.eclipse.ui.navigator 2 0 2016-03-31 08:09:29.243
!MESSAGE Can't find Navigator Content Descriptor with id: org.eclipse.jst.servlet.ui.EnhancedJavaRendering
0    [Worker-3] ERROR org.eclipse.ocl.pivot.internal.resource.StandaloneProjectMap  - Conflicting access to 'platform:/resource/org.eclipse.ocl.pivot/model-gen/oclstdlib.ecore' or 'platform:/plugin/org.eclipse.ocl.pivot/model-gen/oclstdlib.ecore' already accessed as 'http://www.eclipse.org/ocl/2015/Library'

!ENTRY org.apache.log4j 4 0 2016-03-31 08:09:32.981
!MESSAGE org.eclipse.ocl.pivot.internal.resource.StandaloneProjectMap  - Conflicting access to 'platform:/resource/org.eclipse.ocl.pivot/model-gen/oclstdlib.ecore' or 'platform:/plugin/org.eclipse.ocl.pivot/model-gen/oclstdlib.ecore' already accessed as 'http://www.eclipse.org/ocl/2015/Library'

337  [Worker-3] ERROR org.eclipse.ocl.pivot.internal.resource.StandaloneProjectMap  - Conflicting access to 'platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore' or 'platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore' already accessed as 'http://www.eclipse.org/emf/2002/Ecore'

!ENTRY org.apache.log4j 4 0 2016-03-31 08:09:33.315
!MESSAGE org.eclipse.ocl.pivot.internal.resource.StandaloneProjectMap  - Conflicting access to 'platform:/resource/org.eclipse.emf.ecore/model/Ecore.ecore' or 'platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore' already accessed as 'http://www.eclipse.org/emf/2002/Ecore'


!ENTRY org.eclipse.sirius 2 0 2016-03-31 08:09:45.206
!MESSAGE No icon is available for the tool Container. A default icon has been set instead.

!ENTRY org.eclipse.sirius 2 0 2016-03-31 08:09:45.207
!MESSAGE No icon is available for the tool Link. A default icon has been set instead.

!ENTRY org.eclipse.sirius 2 0 2016-03-31 08:09:45.210
!MESSAGE No icon is available for the tool Volumes From. A default icon has been set instead.
!ENTRY org.eclipse.sirius 4 0 2016-03-31 08:09:49.846
!MESSAGE Error while modifying model
!STACK 0
org.eclipse.sirius.ecore.extender.business.api.accessor.exception.MetaClassNotFoundException: docker.Machine_VirtualBox
	at org.eclipse.sirius.ecore.extender.business.api.accessor.ModelAccessor.createInstance(ModelAccessor.java:128)
	at org.eclipse.sirius.business.internal.helper.task.operations.CreateInstanceTask.execute(CreateInstanceTask.java:73)
	at org.eclipse.sirius.business.internal.helper.task.ExecuteToolOperationTask.executeTask(ExecuteToolOperationTask.java:103)
	at org.eclipse.sirius.business.internal.helper.task.ExecuteToolOperationTask.execute(ExecuteToolOperationTask.java:88)
	at org.eclipse.sirius.business.api.helper.task.TaskExecutor.operation(TaskExecutor.java:103)
	at org.eclipse.sirius.business.api.helper.task.TaskExecutor.execute(TaskExecutor.java:65)
	at org.eclipse.sirius.tools.api.command.SiriusCommand.doExecute(SiriusCommand.java:80)
	at org.eclipse.emf.transaction.RecordingCommand.execute(RecordingCommand.java:135)
	at org.eclipse.sirius.diagram.ui.tools.api.command.GMFCommandWrapper.doExecuteWithResult(GMFCommandWrapper.java:103)
	at org.eclipse.gmf.runtime.emf.commands.core.command.AbstractTransactionalCommand.doExecute(AbstractTransactionalCommand.java:247)
	at org.eclipse.emf.workspace.AbstractEMFOperation.execute(AbstractEMFOperation.java:150)
	at org.eclipse.gmf.runtime.common.core.command.CompositeCommand.doExecuteWithResult(CompositeCommand.java:403)
	at org.eclipse.gmf.runtime.common.core.command.AbstractCommand.execute(AbstractCommand.java:134)
	at org.eclipse.gmf.runtime.common.core.command.CompositeCommand.doExecuteWithResult(CompositeCommand.java:403)
	at org.eclipse.gmf.runtime.common.core.command.AbstractCommand.execute(AbstractCommand.java:134)
	at org.eclipse.sirius.diagram.ui.tools.internal.commands.WrappingCommandIgnoringAffectedFiles.execute(WrappingCommandIgnoringAffectedFiles.java:124)
	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:516)
	at org.eclipse.sirius.diagram.ui.tools.internal.editor.DDiagramCommandStack.execute(DDiagramCommandStack.java:71)
	at org.eclipse.sirius.diagram.ui.tools.internal.editor.DDiagramCommandStack.execute(DDiagramCommandStack.java:52)
	at org.eclipse.gmf.runtime.diagram.ui.parts.DiagramCommandStack.execute(DiagramCommandStack.java:156)
	at org.eclipse.gef.dnd.AbstractTransferDropTargetListener.handleDrop(AbstractTransferDropTargetListener.java:339)
	at org.eclipse.gef.dnd.TemplateTransferDropTargetListener.handleDrop(TemplateTransferDropTargetListener.java:115)
	at org.eclipse.gef.dnd.AbstractTransferDropTargetListener.drop(AbstractTransferDropTargetListener.java:183)
	at org.eclipse.jface.util.DelegatingDropAdapter$3.run(DelegatingDropAdapter.java:219)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.util.DelegatingDropAdapter.drop(DelegatingDropAdapter.java:216)
	at org.eclipse.swt.dnd.DNDListener.handleEvent(DNDListener.java:91)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
	at org.eclipse.swt.dnd.DropTarget.drop(DropTarget.java:728)
	at org.eclipse.swt.dnd.DropTarget.performDragOperation(DropTarget.java:742)
	at org.eclipse.swt.dnd.DropTarget.dropTargetProc(DropTarget.java:456)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSView.dragImage(NSView.java:150)
	at org.eclipse.swt.dnd.DragSource.drag(DragSource.java:398)
	at org.eclipse.swt.dnd.DragSource$1.handleEvent(DragSource.java:219)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
```

Any idea ?

**Comment by fifiant** [comment]
It is fixed.
