### ISSUE TITLE
Open occic file with OCCI Editor

### ISSUE THREAD

**Issue by mehdiAhmed** [occiware/ecore#79]
When I Generate an OCCI Configuration file  with just one resource (as example), I cannot open the `occic` file by using OCCI Editor. I Obtain an exception  `Editor could not be initialized.`

```
java.lang.RuntimeException: No EObjectDescription could be found in Scope Entity(Resource).kind for Kind
Semantic Object: Configuration.resources[0]->Resource
URI: temp.occi
EStructuralFeature: occi::Entity.kind
    at org.eclipse.xtext.serializer.diagnostic.ISerializationDiagnostic$ExceptionThrowingAcceptor.accept(ISerializationDiagnostic.java:131)
    at org.eclipse.xtext.serializer.tokens.CrossReferenceSerializer.getCrossReferenceNameFromScope(CrossReferenceSerializer.java:131)
...
```

The occic file generated is:

```
<?xml version="1.0" encoding="ASCII"?>
<occi:Configuration xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:occi="http://schemas.ogf.org/occi">
  <resources id="cb616c21-cbc3-46a5-bdc8-713892a41c7c">
    <kind href="../../plugin/org.occiware.clouddesigner.occi/model/Core.occie#//@kinds[term='resource']"/>
    <attributes name="occi.core.id" value="cb616c21-cbc3-46a5-bdc8-713892a41c7c"/>
  </resources>
</occi:Configuration>

```

**Comment by philippemerle** [comment]
I tested your configuration file with the latest Cloud Designer.
Firstly, I updated xmlns:occi by adding suffix /core/ecore (see issue#30):
```
<?xml version="1.0" encoding="ASCII"?>
<occi:Configuration xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:occi="http://schemas.ogf.org/occi/core/ecore">
  <resources id="cb616c21-cbc3-46a5-bdc8-713892a41c7c">
    <kind href="../../plugin/org.occiware.clouddesigner.occi/model/Core.occie#//@kinds[term='resource']"/>
    <attributes name="occi.core.id" value="cb616c21-cbc3-46a5-bdc8-713892a41c7c"/>
  </resources>
</occi:Configuration>
```
Then I obtained the same error that you when loading the file with OCCI Editor:(

Then I added the usage of OCCI Core (here is the error):
```
<?xml version="1.0" encoding="ASCII"?>
<occi:Configuration xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:occi="http://schemas.ogf.org/occi/core/ecore">
  <use href="http://schemas.ogf.org/occi/core#/"/>
  <resources id="cb616c21-cbc3-46a5-bdc8-713892a41c7c">
    <kind href="../../plugin/org.occiware.clouddesigner.occi/model/Core.occie#//@kinds[term='resource']"/>
    <attributes name="occi.core.id" value="cb616c21-cbc3-46a5-bdc8-713892a41c7c"/>
  </resources>
</occi:Configuration>
```
Then I loaded this configuration file with OCCI Editor successfully and see:
```
configuration
use "http://schemas.ogf.org/occi/core#/"
resource "cb616c21-cbc3-46a5-bdc8-713892a41c7c" : core.resource {
	state occi.core.id = "cb616c21-cbc3-46a5-bdc8-713892a41c7c"
}
```
Youpi :)

Finally, I updated the kind element in order to use extension scheme instead of file path into href attribute (see issue#30).
Following is the final version:
```
<?xml version="1.0" encoding="ASCII"?>
<occi:Configuration xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:occi="http://schemas.ogf.org/occi/core/ecore">
  <use href="http://schemas.ogf.org/occi/core#/"/>
  <resources id="cb616c21-cbc3-46a5-bdc8-713892a41c7c">
    <kind href="http://schemas.ogf.org/occi/core#//@kinds[term='resource']"/>
    <attributes name="occi.core.id" value="cb616c21-cbc3-46a5-bdc8-713892a41c7c"/>
  </resources>
</occi:Configuration>
```

Could you try it with the latest cloud designer?

**Comment by mehdiAhmed** [comment]
It works. Thanks
